Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/BlockComments:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Next:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
