current:
  - name: 'Aaron Bassett'
    email: 'aaron.bassett@vonage.com'
    twitter: 'aaronbassett'
  - name: 'Alex Lakatos'
    email: 'alex.lakatos@vonage.com'
    twitter: 'lakatos88'  
  - name: 'Amanda Folson'
    email: 'amanda.folson@vonage.com'
    role: 'Developer Relations Manager'
    twitter: 'AmbassadorAwsum'
  - name: 'Britt Barak'
    email: 'britt.barak@vonage.com'
    twitter: 'brittBarak'
  - name: 'Chris Guzman'
    email: 'chris.guzman@vonage.com'
    twitter: 'speaktochris'
  - name: 'Lorna Mitchell'
    email: 'lorna.mitchell@vonage.com'
    twitter: 'lornajane'
  - name: 'Mark Smith'
    email: 'mark.smith@nexmo.com'
    twitter: 'judy2k'  
  - name: 'Martyn Davies'
    email: 'martyn.davies@vonage.com'
    twitter: 'martynd'
  - name: 'Michael Heap'
    email: 'michael.heap@vonage.com'
    twitter: 'mheap'      
  - name: 'Olia Dukova'
    email: 'olia.dukova@nexmo.com'
    twitter: 'oliadukova'
    role: 'Community Manager'
  - name: 'Phil Leggetter'
    email: 'phil.leggetter@vonage.com'
    role: 'Director of Developer Relations'
    twitter: 'leggetter'
  - name: 'Rabeb Othmani'
    email: 'rabeb.othmani@vonage.com'
    twitter: 'Rabeb_Othmani'
  - name: 'Sam Machin'
    email: 'sam.machin@nexmo.com'
    twitter: 'sammachin'
  - name: 'Steve Crow'
    email: 'steve.crow@vonage.com'
    twitter: 'cr0wst'
  - name: 'Tony Bedford'
    email: 'tony.bedford@vonage.com'
    role: 'Technical Writer'
  - name: 'Myrsini Koukiasa'
    email: 'myrsini.koukiasa@vonage.com'
    twitter: 'myrsiningos'
    role: 'Community Manager'
  - name: 'Mark Lewin'
    email: 'mark.lewin@vonage.com'
    twitter: 'devtechwriter'
    role: 'Technical Writer'
alumni:
  - name: 'Adam Butler'
    email: 'adam.butler@vonage.com'
    role: 'Nexmo Developer Technical Lead'
    twitter: 'labfoo'
  - name: 'Tom Morris'
    email: 'tom.morris@vonage.com'
    role: 'Technical Writer'
    twitter: 'tommorris'
